import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getContent } from "@/lib/content";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Handover Site",
  description: "Generated by Handover",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = await getContent();
  const theme = content.theme;

  return (
    <html lang="en">
      <head>
        <style>{`
          :root {
            --primary: ${theme.primary_color};
            --secondary: ${theme.secondary_color};
            --background: ${theme.background_color};
            --foreground: ${theme.text_color};
          }
          body {
            background-color: var(--background);
            color: var(--foreground);
          }
        `}</style>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
