import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getContent } from "@/lib/content";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Handover Site",
  description: "Generated by Handover",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = await getContent();
  const theme = content.theme;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <style>{`
          :root {
            --site-primary: ${theme.primary_color};
            --site-secondary: ${theme.secondary_color};
            --site-background: ${theme.background_color};
            --site-foreground: ${theme.text_color};
          }
          /* We don't apply body styles here anymore to avoid conflict with Admin */
        `}</style>
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
